class AccountManagerMainPageLocators():
    LOC_LOAN_LIST_VIEW_ID = "loan-list-view"
    LOC_USER_INFO_PANEL_CSS = "#loan-list-view > div:nth-child(1)"
    LOC_EDIT_MY_INFO_BUTTON_CLASS = "eu-btn-secondary"
    LOC_EDIT_MY_INFO_MODAL_CLASS = "modal-dialog"
    LOC_EDIT_MY_INFO_MODAL_BODY_CLASS = "modal-body"
    LOC_EDIT_MY_INFO_MODAL_CLOSE_BUTTON_CLASS = "modal-exit-btn"
    LOC_EDIT_MY_INFO_MODAL_HEADER_CLASS = "mt-0"
    LOC_EDIT_MY_INFO_MODAL_SUBTEXT_CLASS = "subtext"
    LOC_EDIT_MY_INFO_MODAL_EDIT_FORM_ID = "edit-user-info-form"
    LOC_EDIT_MY_INFO_MODAL_EMAIL_ID = "email"
    LOC_EDIT_MY_INFO_MODAL_PRIMARY_PHONE_ID = "phone"
    LOC_EDIT_MY_INFO_MODAL_SECONDARY_PHONE_ID = "secondary-phone"
    LOC_EDIT_MY_INFO_MODAL_ADDRESS_ID = "address"
    LOC_EDIT_MY_INFO_MODAL_NAME_ID = "name"
    LOC_EDIT_MY_INFO_MODAL_DOB_MONTH_ID = "dob-month-input"
    LOC_EDIT_MY_INFO_MODAL_DOB_DAY_ID = "dob-day-input"
    LOC_EDIT_MY_INFO_MODAL_DOB_YEAR_ID = "dob-year-input"
    LOC_EDIT_MY_INFO_CONFIRM_BUTTON_CSS = "button.wide.eu-btn.papaya"
    LOC_EDIT_MY_INFO_CONFIRM_BUTTON_XPATH = '//*[@id="edit-user-info-form"]/div[1]/div[3]/div/button[1]'
    LOC_EDIT_MY_INFO_CANCEL_BUTTON_CSS = "button.wide.eu-btn-secondary.papaya"
    LOC_INVALID_ADDRESS_MODAL_ID = "address-invalid-address-form"
    LOC_INVALID_ADDRESS_MODAL_EDIT_ID = "address-invalid-change-btn"
    LOC_INVALID_ADDRESS_MODAL_CONFIRM_ID = "address-invalid-certify-btn"
    LOC_INVALID_ADDRESS_MODAL_ORIGINAL_INPUT_CLASS = "address-address-original-input"
    LOC_LIST_LOAN_OBJECT_CSS = "#loan-list-view > a > div"
    
